<a href="https://colab.research.google.com/github/VinothL/tf_learning/blob/main/Intro_to_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import TensorFlow
import tensorflow as tf

In [2]:
print(tf.__version__) # find the version number (should be 2.x+)

2.7.0


In [3]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim


0

In [9]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10,10])
printVector = print('The values within the vector: ' + vector + '\n')
print('The dimension of the vector : '+ vector.ndim)
with tf.Session() as sess:     
           print(sess.run(printVector))
           print (printVector.eval())

TypeError: ignored

In [10]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
anotherMatric = tf.constant([[10.0,11.0],[9.2,8.2],[7.5,7.9]],dtype=tf.float32)

In [13]:
anotherMatric

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10. , 11. ],
       [ 9.2,  8.2],
       [ 7.5,  7.9]], dtype=float32)>

In [14]:
#Creating the tensors with tf.Variables and tf.constant
changeableVector = tf.Variable([[1,2]])
unChangeableVector = tf.constant([1,2])
changeableVector,unChangeableVector

(<tf.Variable 'Variable:0' shape=(1, 2) dtype=int32, numpy=array([[1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [30]:
changeableVector

<tf.Variable 'Variable:0' shape=(1, 2) dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [32]:
changeableVector.assign([[6,7]])
changeableVector

<tf.Variable 'Variable:0' shape=(1, 2) dtype=int32, numpy=array([[6, 7]], dtype=int32)>

Creating the Random tensors using normal distribution and understanding the seed functionality

In [36]:
#Creating the random tensors
normalMat1 = tf.random.Generator.from_seed(42)
normalMat1 = normalMat1.normal(shape = (2,3))
normalMat1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [38]:
onesMat = tf.ones(shape=(2,3))
zerosMat = tf.zeros(shape=(2,3))
onesMat,zerosMat

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

Using numpy array inside Tensor

In [39]:
import numpy as np



In [43]:
np_array = np.arange(1,25,dtype=np.int32)
tensor_matrix = tf.constant(np_array,shape=[2,4,3])
tensor_matrix

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [45]:
rank4_tensors = tf.zeros(shape=[2,3,4,5])
rank4_tensors.ndim

4

In [46]:
rank4_tensors

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [47]:
rank4_tensors.ndim, rank4_tensors.shape, tf.size(rank4_tensors)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [50]:
tf_m1 = tf.constant((1,2,3),dtype=tf.int32)
tf_m1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [53]:
tf.random.set_seed(7)
mx1 = tf.random.normal((2,3),dtype=tf.float32)
mx1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.5983449 ,  0.06276207,  0.14631742],
       [ 0.48481876, -0.23572342,  0.61806035]], dtype=float32)>

In [54]:
tf.random.set_seed(7)
mx2 = tf.random.normal((2,3),dtype=tf.float32,seed=8)
mx2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.4218376 , -0.7892279 ,  0.7690075 ],
       [-1.3323994 ,  0.8665976 , -0.16573197]], dtype=float32)>

In [57]:
tf.random.set_seed(7)
mx3 = tf.random.normal((3,2),dtype=tf.float32,seed=9)
mx3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.1868204 , -1.1004789 ],
       [-0.13537489, -1.2320284 ],
       [-0.8370753 , -0.11157034]], dtype=float32)>

In [58]:
print(tf.config.list_physical_devices('GPU'))

[]


In [ ]:
Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
Find the shape, rank and size of the tensors you created in 1.
Create two tensors containing random values between 0 and 1 with shape [5, 300].
Multiply the two tensors you created in 3 using matrix multiplication.
Multiply the two tensors you created in 3 using dot product.
Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
Find the min and max values of the tensor you created in 6.
Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
One-hot encode the tensor you created in 9.

In [59]:
v1 = tf.constant((2,3))
v1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [61]:
s1 = tf.constant(1)
s1

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [63]:
m1 = tf.random.Generator.from_seed(2)
m1 = m1.normal(shape=(2,3,4))
m1

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.1012345 , -0.2744976 ,  1.4204658 ,  1.2609464 ],
        [-0.43640924, -1.9633987 , -0.06452483, -1.056841  ],
        [ 1.0019137 ,  0.6735137 ,  0.06987712, -1.4077919 ]],

       [[ 1.0278524 ,  0.27974114, -0.01347923,  1.845181  ],
        [ 0.97061104, -1.0242516 , -0.6544423 , -0.29738766],
        [-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018]]],
      dtype=float32)>

In [66]:
t1 = tf.random.Generator.from_seed(3)
t1 = t1.normal(shape = (2,3,4,5))


In [67]:
t1.shape , t1.ndim, tf.size(t1)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [68]:
t2 = tf.zeros(shape = (5,400))
t3 = tf.ones(shape=(5,400))

In [72]:
t4 = np.matmul(t2,tf.transpose(t3))

In [74]:
t5 = tf.tensordot(t2,tf.transpose(t3),axes=1)